### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by florentmorin** [WeTransfer/WeScan#172]
Did you plan to support Swift Package Manager?

**Comment by jcampbell05** [comment]
I believe we will once it is out of public beta.

**Comment by AvdLee** [comment]
Challenge will be the resource files as this is not supported with package manager. We'll have to see what we can do there.

**Comment by AvdLee** [comment]
Keeping this open as we will add support once SPM supports resources

**Comment by AvdLee** [comment]
SPM Support for resources is coming in Swift 5.3!

**Comment by AvdLee** [comment]
I'm happy to announce a PR is finally open for SPM support!

**Comment by florentmorin** [comment]
Thank you @AvdLee 👍

**Comment by wetransferplatform** [comment]
The pull request #279 that closed this issue was merged and released as part of [Release 1.8.0](https://github.com/WeTransfer/WeScan/releases/tag/1.8.0) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
