### ISSUE TITLE
I get thread safety check from `CaptureSessionManager`

### ISSUE THREAD

**Issue by sami79031** [WeTransfer/WeScan#380]
That happens almost every time I start the `ImageScannerController`. I'm using it from the SwiftUI context iOS 16. Nothing special.

-[AVCaptureSession startRunning] should be called from background thread. Calling it on the main thread can lead to UI unresponsiveness

<img width="1003" alt="Screenshot 2024-03-28 at 6 37 55 PM" src="https://github.com/WeTransfer/WeScan/assets/9218154/84cc032e-1716-4335-8438-4a876124c70c">

**Comment by gantaa** [comment]
I was in the process of creating a PR to contribute for this because I am also seeing the log on latest WeScan code.  But then I saw this:  

https://github.com/WeTransfer/WeScan/commit/699b7477deb3dd3d47b54693021cceffab8dde81

It looks like the correct code for this fix.  It is committed to master, and yet I still see the log appear when using WeScan 3.0.0

Any ideas @BasThomas or @hajunho?

**Comment by BasThomas** [comment]
3.0.0 does not include the changes present on the main branch. Can you update your reference to be the main branch rather than `3.0.0`, to see if the issue is still present then? We can look into creating a new release from there.
